<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Inicio</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
 	
 	<link rel="stylesheet" href="css/bootstrap.min.css">
  	<script src="js/jquery-1.11.2.min.js"></script>
  	<script src="js/bootstrap.min.js"></script>
	
	<link rel="stylesheet" href="css/estilosfer.css">
	<script src="js/jquery.functions.js" type="text/javascript"></script>

</head>
	<div class="container">
		<header>
			<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-1">
							<span class="sr-only">Menu</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a href="index.php" class="navbar-brand">Stardelgado</a>
					</div>
					
					<div class="collapse navbar-collapse" id="navbar-1">
						<div class="nav navbar-nav ">
							<li><a href="">Inicio</a></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="bottom">Area Docencia <span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a href="ListarDocente.php">Docente</a></li>
									<li><a href="#">Pais</a></li>
									<li class="divider"></li>
									<li><a href="#">Otros</a></li>
								</ul>
							</li>

							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="bottom">Dropdown <span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a href="#">item #1</a></li>
									<li><a href="#">item #2</a></li>
									<li class="divider"></li>
									<li><a href="#">item #4</a></li>
								</ul>
							</li>

						</div>
					</div>
				</div>
			</nav>	
		</header>
	</div>
</html>