<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Inicio</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
 	
 	<link rel="stylesheet" href="css/bootstrap.min.css">
  	<script src="js/jquery-1.11.2.min.js"></script>
  	<script src="js/bootstrap.min.js"></script>
  	<style>
		body{
			padding-top:80px;
		}
	</style>  
</head>
	<div class="container">
		<br>
		<header>
			<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-1">
							<span class="sr-only">Menu</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a href="index.php" class="navbar-brand">Stardelgado</a>
					</div>
					
					<div class="collapse navbar-collapse" id="navbar-1">
						<div class="nav navbar-nav ">
							<li><a href="">Inicio Para Empresa</a></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="bottom">Mi Empresa <span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a href="#">Reporte de Ganancia</a></li>
									<li><a href="#">Opcion 1</a></li>
									<li class="divider"></li>
									<li><a href="#">Opcion 2</a></li>
								</ul>
							</li>
						</div>
					</div>
				</div>
			</nav>	
		</header>
	</div>


</html>
